// Fetch the Scorpius-Centaurus clusters of Ratzenboeck et al. 2023 (A&A 677,
// A59, table 3: 37 SigMA clusters from Gaia) from VizieR and write
// www/js/scocen.js. Usage: node scripts/import-sco-cen.mjs
import { writeFileSync } from 'node:fs';

const TAP = 'https://tapvizier.cds.unistra.fr/TAPVizieR/tap/sync';
// ADQL cannot tell E_GLON from e_GLON, so take every column and pick by name.
const query = 'SELECT * FROM "J/A+A/677/A59/table3" ORDER BY recno';
const url = `${TAP}?${new URLSearchParams({ request: 'doQuery', lang: 'adql', format: 'csv', query })}`;
const text = await (await fetch(url)).text();
const [head, ...lines] = text.trim().split('\n');
const cols = head.split(',');
const rows = lines.map((line) => {
  const f = line.match(/("[^"]*"|[^,]*)(,|$)/g).map((s) => s.replace(/,$/, '').replace(/^"|"$/g, '').trim());
  const get = (name) => f[cols.indexOf(name)];
  const num = (name) => Number(get(name));
  // Spread of members: the mean of the two quoted half-widths, in degrees
  // of longitude and in parsecs of distance.
  return [get('Region'), get('Group'), num('GLON'), num('GLAT'), num('Dist'),
    Number(((num('E_GLON') + num('e_GLON')) / 2).toFixed(2)), Number(((num('E_Dist') + num('e_Dist')) / 2).toFixed(1)), num('Nr')];
});
if (rows.length !== 37) throw new Error(`expected 37 clusters, got ${rows.length}`);
const header = `// Generated by scripts/import-sco-cen.mjs from Ratzenboeck et al. 2023
// (A&A 677, A59, table 3) via VizieR on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.
// Per cluster: subregion, name, galactic l and b (degrees), distance (pc),
// half-width of the members in longitude (degrees) and in distance (pc),
// and the number of Gaia members.
`;
writeFileSync(new URL('../www/js/scocen.js', import.meta.url),
  `${header}export const SCO_CEN = [\n${rows.map((r) => `  ${JSON.stringify(r)},`).join('\n')}\n];\n`);
console.log(`${rows.length} clusters, ${rows.reduce((s, r) => s + r[7], 0)} members`);
