// Import the WISE catalog of Galactic HII regions (Anderson et al. 2014,
// VizieR J/ApJS/212/1) and write www/js/hii.js. Only known HII regions and
// members of known groups (classes K and G) with a distance are kept.
// Usage: node scripts/import-hii.mjs
import { writeFileSync } from 'node:fs';

const URL_ = 'https://vizier.cds.unistra.fr/viz-bin/asu-tsv?-source=J/ApJS/212/1/wisecat'
  + '&-out.max=unlimited&-out=Cl,GLON,GLAT,Rad,HIIName,Dist,Meth&Dist=%3E0';
const text = await (await fetch(URL_)).text();
const rows = text.split('\n').filter((l) => l && !l.startsWith('#')).slice(3);

const out = [];
for (const row of rows) {
  const [cl, glon, glat, rad, names, dist, meth] = row.split('\t').map((s) => s.trim());
  if (!'KG'.includes(cl) || !cl || !Number(dist)) continue;
  // The HII region names list catalog designations first; keep a common
  // name (Orion A, W40, S106) when there is one.
  const name = names.split(';').map((s) => s.trim()).filter((s) => s && !/^G\d{3}\.\d{3}[+-]/.test(s)).pop() || '';
  out.push(`  [${JSON.stringify(name)}, ${Number(glon)}, ${Number(glat)}, ${Number(dist)}, ${Number(rad)}, ${meth.startsWith('Parallax') ? 1 : 0}],`);
}
writeFileSync(new URL('../www/js/hii.js', import.meta.url), `// Generated by scripts/import-hii.mjs from the WISE catalog of Galactic HII
// regions (Anderson et al. 2014, VizieR J/ApJS/212/1) on ${new Date().toISOString().slice(0, 10)}.
// Do not edit by hand. Known regions and group members with a distance.
// Per region: common name ('' if none), galactic l and b (degrees), distance
// from the Sun (kpc), angular radius (arcsec), 1 if the distance is a maser
// parallax rather than kinematic.
export const HII_REGIONS = [
${out.join('\n')}
];
`);
console.log(`${out.length} regions, ${out.filter((l) => l.endsWith(', 1],')).length} with parallax distances`);
